### ISSUE TITLE
Research on DialoGPT

### ISSUE THREAD

**Issue by STAVAN-2710** [STAVAN-2710/mental-health-assistant#1]
@MDheeraj500 , @STAVAN-2710 

### Description

We are progressing to the integration phase for our project (the next step following the setting up of the GitHub repo). This task involves working with the pre-trained conversational model **DialoGPT** and integrating it with **EmoBERTa** for emotion recognition.

- Learn to utilize the APIs for both models and explore how they can be integrated into environments like Google Colab or Kaggle.
- Focus on understanding DialoGPT’s dialogue generation capabilities, and how EmoBERTa can enhance the assistant’s emotional intelligence.

### Next  Steps

- Explore API documentation for DialoGPT and EmoBERTa.
- Experiment with Colab/Kaggle to understand model integration and interaction.

**Comment by MDheeraj500** [comment]
Let's create a project management Kanban Board and move this issue to the board in the "In-progress" status and close this issue.
